# Generated by Django 5.2.12 on 2026-03-30 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('project_created', '📁 Project Created'), ('task_created', '✅ Task Created'), ('task_assigned', '👤 Task Assigned'), ('task_updated', '🔄 Task Updated'), ('task_completed', '🎉 Task Completed'), ('login', '🚪 User Login')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner_app.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner_app.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
